# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/hero/v1alpha/hero.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dproto/hero/v1alpha/hero.proto\x12\x0chero.v1alpha\";\n\x04Hero\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05power\x18\x03 \x01(\t\x12\n\n\x02hp\x18\x04 \x01(\t\"A\n\nGetRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05power\x18\x03 \x01(\t\x12\n\n\x02hp\x18\x04 \x01(\t\"/\n\x0bGetResponse\x12 \n\x04hero\x18\x01 \x03(\x0b\x32\x12.hero.v1alpha.Hero\"5\n\nAddRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05power\x18\x02 \x01(\t\x12\n\n\x02hp\x18\x03 \x01(\t\"/\n\x0b\x41\x64\x64Response\x12 \n\x04hero\x18\x01 \x01(\x0b\x32\x12.hero.v1alpha.Hero\"1\n\rUpdateRequest\x12 \n\x04hero\x18\x01 \x01(\x0b\x32\x12.hero.v1alpha.Hero\"2\n\x0eUpdateResponse\x12 \n\x04hero\x18\x01 \x01(\x0b\x32\x12.hero.v1alpha.Hero\"2\n\x0e\x44\x65leteResponse\x12 \n\x04hero\x18\x01 \x01(\x0b\x32\x12.hero.v1alpha.Hero\"\x1b\n\rDeleteRequest\x12\n\n\x02id\x18\x01 \x01(\t2\x93\x02\n\x0fHeroCRUDService\x12:\n\x03Get\x12\x18.hero.v1alpha.GetRequest\x1a\x19.hero.v1alpha.GetResponse\x12:\n\x03\x41\x64\x64\x12\x18.hero.v1alpha.AddRequest\x1a\x19.hero.v1alpha.AddResponse\x12\x43\n\x06Update\x12\x1b.hero.v1alpha.UpdateRequest\x1a\x1c.hero.v1alpha.UpdateResponse\x12\x43\n\x06\x44\x65lete\x12\x1b.hero.v1alpha.DeleteRequest\x1a\x1c.hero.v1alpha.DeleteResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.hero.v1alpha.hero_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_HERO']._serialized_start=47
  _globals['_HERO']._serialized_end=106
  _globals['_GETREQUEST']._serialized_start=108
  _globals['_GETREQUEST']._serialized_end=173
  _globals['_GETRESPONSE']._serialized_start=175
  _globals['_GETRESPONSE']._serialized_end=222
  _globals['_ADDREQUEST']._serialized_start=224
  _globals['_ADDREQUEST']._serialized_end=277
  _globals['_ADDRESPONSE']._serialized_start=279
  _globals['_ADDRESPONSE']._serialized_end=326
  _globals['_UPDATEREQUEST']._serialized_start=328
  _globals['_UPDATEREQUEST']._serialized_end=377
  _globals['_UPDATERESPONSE']._serialized_start=379
  _globals['_UPDATERESPONSE']._serialized_end=429
  _globals['_DELETERESPONSE']._serialized_start=431
  _globals['_DELETERESPONSE']._serialized_end=481
  _globals['_DELETEREQUEST']._serialized_start=483
  _globals['_DELETEREQUEST']._serialized_end=510
  _globals['_HEROCRUDSERVICE']._serialized_start=513
  _globals['_HEROCRUDSERVICE']._serialized_end=788
# @@protoc_insertion_point(module_scope)
