# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/lieu/v1alpha/lieu.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dproto/lieu/v1alpha/lieu.proto\x12\x0clieu.v1alpha\"X\n\x04LIEU\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06\x66ormat\x18\x02 \x01(\t\x12 \n\x18\x65tablissement_plateforme\x18\x03 \x01(\t\x12\x12\n\nsalle_lien\x18\x04 \x01(\t\"^\n\nGetRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06\x66ormat\x18\x02 \x01(\t\x12 \n\x18\x65tablissement_plateforme\x18\x03 \x01(\t\x12\x12\n\nsalle_lien\x18\x04 \x01(\t\"/\n\x0bGetResponse\x12 \n\x04lieu\x18\x01 \x03(\x0b\x32\x12.lieu.v1alpha.LIEU\"R\n\nAddRequest\x12\x0e\n\x06\x66ormat\x18\x01 \x01(\t\x12 \n\x18\x65tablissement_plateforme\x18\x02 \x01(\t\x12\x12\n\nsalle_lien\x18\x03 \x01(\t\"/\n\x0b\x41\x64\x64Response\x12 \n\x04lieu\x18\x01 \x01(\x0b\x32\x12.lieu.v1alpha.LIEU\"1\n\rUpdateRequest\x12 \n\x04lieu\x18\x01 \x01(\x0b\x32\x12.lieu.v1alpha.LIEU\"2\n\x0eUpdateResponse\x12 \n\x04lieu\x18\x01 \x01(\x0b\x32\x12.lieu.v1alpha.LIEU\"2\n\x0e\x44\x65leteResponse\x12 \n\x04lieu\x18\x01 \x01(\x0b\x32\x12.lieu.v1alpha.LIEU\"\x1b\n\rDeleteRequest\x12\n\n\x02id\x18\x01 \x01(\t2\x93\x02\n\x0fLieuCRUDService\x12:\n\x03Get\x12\x18.lieu.v1alpha.GetRequest\x1a\x19.lieu.v1alpha.GetResponse\x12:\n\x03\x41\x64\x64\x12\x18.lieu.v1alpha.AddRequest\x1a\x19.lieu.v1alpha.AddResponse\x12\x43\n\x06Update\x12\x1b.lieu.v1alpha.UpdateRequest\x1a\x1c.lieu.v1alpha.UpdateResponse\x12\x43\n\x06\x44\x65lete\x12\x1b.lieu.v1alpha.DeleteRequest\x1a\x1c.lieu.v1alpha.DeleteResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.lieu.v1alpha.lieu_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_LIEU']._serialized_start=47
  _globals['_LIEU']._serialized_end=135
  _globals['_GETREQUEST']._serialized_start=137
  _globals['_GETREQUEST']._serialized_end=231
  _globals['_GETRESPONSE']._serialized_start=233
  _globals['_GETRESPONSE']._serialized_end=280
  _globals['_ADDREQUEST']._serialized_start=282
  _globals['_ADDREQUEST']._serialized_end=364
  _globals['_ADDRESPONSE']._serialized_start=366
  _globals['_ADDRESPONSE']._serialized_end=413
  _globals['_UPDATEREQUEST']._serialized_start=415
  _globals['_UPDATEREQUEST']._serialized_end=464
  _globals['_UPDATERESPONSE']._serialized_start=466
  _globals['_UPDATERESPONSE']._serialized_end=516
  _globals['_DELETERESPONSE']._serialized_start=518
  _globals['_DELETERESPONSE']._serialized_end=568
  _globals['_DELETEREQUEST']._serialized_start=570
  _globals['_DELETEREQUEST']._serialized_end=597
  _globals['_LIEUCRUDSERVICE']._serialized_start=600
  _globals['_LIEUCRUDSERVICE']._serialized_end=875
# @@protoc_insertion_point(module_scope)
